# https://www.wilsonwilson.dev/articles/flutter-build-yaml/

targets:
  $default:
    builders:
      freezed|freezed:
        enabled: true
        generate_for:
          - "lib/core/models/audio_player_state.dart"
          - "lib/core/models/audio_record.dart"
          - "lib/core/models/audio_recorder_state.dart"
      mockito|mockBuilder:
        enabled: true
        generate_for:
          - "test/logics/audio_recorder_logic_test.dart"
          - "test/repositories/storage_repository_test.dart"
