name: magic_record
description: A Flutter project to manage voice recorder.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'
  flutter: ">=3.7.0"

dependencies:
  cupertino_icons: ^1.0.5
  flutter:
    sdk: flutter
  freezed_annotation: ^2.2.0
  permission_handler: ^10.2.0
  provider: ^6.0.5
  record: ^4.4.4
  just_audio: ^0.9.31

dev_dependencies:
  build_runner: ^2.3.3
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  freezed: ^2.3.2

flutter:
  uses-material-design: true
